spring.application.name=certificacao

# Conexão com o banco MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_projeto
spring.datasource.username=root
spring.datasource.password=Rafa136501

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true